#!/usr/bin/env python
##!/usr/bin/env python2.6
# Author				version		Up-date			Description
#------------------------------------------------------------------------
# T. Ribeiro (SOAR)		0.0			09 Jun 2011     Creation

'''
	
varlook.py - GUI for looking up variability.

	Ribeiro, T., June 2011.
	
'''

import sys,os
from t80sched.gui import gui

if __name__ == "__main__":
	
	gui.logging.basicConfig(format='%(levelname)s:%(asctime)s::%(message)s',
						level=gui.logging.DEBUG)

	
	root = gui.QtGui.QApplication(sys.argv)
	
	usergui = gui.SchedulerGUI()
	
	usergui.initGUI()
	
	usergui.show()
	
	sys.exit(root.exec_())
