#!/usr/bin/env python

################################################################################

from chimera.core.cli import ChimeraCLI, action
from chimera.core.constants import DEFAULT_PROGRAM_DATABASE
from chimera.core.callback import callback
from chimera.util.position import Position
from chimera.util.output import blue, green, red

from chimera.controllers.scheduler.status import SchedulerStatus
from chimera.controllers.scheduler.states import State
from chimera.controllers.scheduler.model import (Session, Program, Point,
												 Expose, PointVerify, AutoFocus)

import re
import sys
import os
import shutil
import time


################################################################################

class ChimeraT80Sched (ChimeraCLI):

	############################################################################
	
	def __init__(self):
		ChimeraCLI.__init__(self, "chimera-sched",
							"Scheduler controller", 0.0, port=9010)

        self.addHelpGroup("SCHEDULER", "Scheduler")
		self.addController(name="scheduler",
						   cls="Scheduler",
						   required=True,
						   help="Scheduler controller to be used",
						   helpGroup="SCHEDULER")

		
	############################################################################


################################################################################

def main():
	cli = ChimeraSched()
		cli.run(sys.argv)
			cli.wait()

################################################################################

if __name__ == '__main__':
	
	main()

################################################################################